export const ADD_PERSON = 'ADD_PERSON'
export const FETCH_PERSON_DATA_SUCCESS = 'FETCH_PERSON_DATA_SUCCESS'
export const FETCH_PERSON_DATA_FAIL = 'FETCH_PERSON_DATA_FAIL'
export const REQUEST_PERSON_DATA = 'REQUEST_PERSON_DATA'