// Actions constants

export const ADD_PERSON = 'ADD_PERSON'
export const FETCH_PERSON_DATA_SUCCESS = 'FETCH_PERSON_DATA_SUCCESS'
export const FETCH_PERSON_DATA_FAIL = 'FETCH_PERSON_DATA_FAIL'
export const REQUEST_PERSON_DATA = 'REQUEST_PERSON_DATA'

export const SORT_TABLE_START = 'SORT_TABLE_START'
export const SORT_TABLE_SUCCESS = 'SORT_TABLE_SUCCESS'

export const GET_TABLE_PAGE = 'GET_TABLE_PAGE'
